// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wolftrack.Database;

namespace wolftrack.Migrations
{
    [DbContext(typeof(WolftrackContext))]
    partial class WolftrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("wolftrack.Models.Pack", b =>
                {
                    b.Property<int>("PackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackId");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("wolftrack.Models.Wolf", b =>
                {
                    b.Property<int>("WolfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PackId")
                        .HasColumnType("int");

                    b.HasKey("WolfId");

                    b.HasIndex("PackId");

                    b.ToTable("Wolves");
                });

            modelBuilder.Entity("wolftrack.Models.Wolf", b =>
                {
                    b.HasOne("wolftrack.Models.Pack", "Pack")
                        .WithMany("Wolves")
                        .HasForeignKey("PackId");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("wolftrack.Models.Pack", b =>
                {
                    b.Navigation("Wolves");
                });
#pragma warning restore 612, 618
        }
    }
}
